### ISSUE TITLE
Could you please provide a pipeline to help taxonomic annotation of viruses?

### ISSUE THREAD

**Issue by MengzhiJ** [snayfach/MGV#10] opened 2021-11-14 04:10 UTC
Hi, 
  I read your article on viruses from the human gut microbiome, which is very meaningful. And these pipeline are helpful for the study of viral metagenome. Here, I would like to ask if you can provide a pipeline to help taxonomic annotation of viruses, as you did in your article.

**Comment by alienn233** [comment] 2022-02-28 01:23
+1

**Comment by lonestarling** [comment] 2022-06-09 02:54
hey guys
have you finished the step of taxonomic annotation？

**Comment by snayfach** [comment] 2022-06-09 03:05
Here's a pipeline that works in a similar way: https://github.com/apcamargo/ictv-mmseqs2-protein-database

**Comment by snayfach** [comment] 2022-06-09 03:06
Duplicate of #1

**Closed by snayfach** 2022-06-09 03:06 UTC

**Comment by lonestarling** [comment] 2022-06-09 03:33
Hi
Stephen
I am so excited for you reply, thank you for your outstanding contribution to this field, really appreciated it, I just wondering can I ask you some help about the study of gut virus of mammals via E-mail.
Best wishes
Lonestarling



At 2022-06-09 11:05:39, "Stephen Nayfach" ***@***.***> wrote:

Here's a pipeline that works in a similar way: https://github.com/apcamargo/ictv-mmseqs2-protein-database
