### ISSUE TITLE
I want to know how to make annotation

### ISSUE THREAD

**Issue by Dorothydu12** [snayfach/MGV#3] opened 2021-09-19 08:29 UTC
Thanks!

**Comment by snayfach** [comment] 2021-10-18 22:49
Not sure what you mean. Can you elaborate?

**Comment by lonestarling** [comment] 2022-06-09 02:56
Hey

have you finished the step of taxonomic annotation?

**Comment by snayfach** [comment] 2022-06-09 03:06
Duplicate of #1

**Closed by snayfach** 2022-06-09 03:06 UTC
