### ISSUE TITLE
Virus classification annotation

### ISSUE THREAD

**Issue by qkqk-hub** [snayfach/MGV#22] opened 2023-04-23 06:47 UTC
Hello, I am very interested in your work, and I would like to express my thanks to him for his great help. May I ask how to classify viruses into DNA, dsDNA, ssDNA, SSDNA-RT, dsRNA, RNA, ssRNA, SSNA-RT, and what tools are available? Thank you again

**Comment by snayfach** [comment] 2023-06-16 01:48
Duplicate of #1

**Closed by snayfach** 2023-06-16 01:48 UTC
